### ISSUE TITLE
rhdf5 not available

### ISSUE THREAD

**Issue by derrik-gratz** [cellgeni/schard#5] opened 2024-05-09 16:23 UTC
Hello, I'm trying to install this package to convert h5ad, but I cannot complete the install as one of the specified dependencies `rhdf5` is unavailable. Even if I install it manually prior to installing the package it still cannot install. I created a pull request to resolve the dependency issue via biocviews specification in the description

#4 

```
install.packages("bioc::rhdf5")
# Downloading packages -------------------------------------------------------
- Downloading rhdf5 from BioCsoft ...           OK [1.2 Mb in 0.13s]
Successfully downloaded 1 package in 0.33 seconds.

The following package(s) will be installed:
- rhdf5 [2.46.1]
These packages will be installed into "/yerkes-cifs/runs/Analysis/2024_Analyses/p00000_Zachary/analysis/renv/library/R-4.3/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: 
# Installing packages --------------------------------------------------------
- Installing rhdf5 ...                          OK [built from source and cached in 12s]
Successfully installed 1 package in 13 seconds.
> install.packages("cellgeni/schard")
# Downloading packages -------------------------------------------------------
- Downloading schard from GitHub ...            OK [7.6 Kb in 0.58s]
Error: package 'rhdf5' is not available

> install.packages("derrik-gratz/schard")
# Downloading packages -------------------------------------------------------
- Downloading schard from GitHub ...            OK [7.6 Kb in 0.5s]
Successfully downloaded 1 package in 1.6 seconds.

The following package(s) will be installed:
- schard [derrik-gratz/schard@main]
These packages will be installed into "/yerkes-cifs/runs/Analysis/2024_Analyses/p00000_Zachary/analysis/renv/library/R-4.3/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: 
# Installing packages --------------------------------------------------------
- Installing schard ...                         OK [built from source and cached in 4.6s]
Successfully installed 1 package in 4.6 seconds.

```

**Comment by iaaka** [comment] 2024-05-10 10:33
Hi @derrik-gratz, thank you for pointing this out. Indeed bioc instruction didn't work as intended. I replaced it with `biocViews` according to your suggestions. I committed it along side with some other rearrangements of dependences, so the [latest commit ](https://github.com/cellgeni/schard/commit/7953f442f66aa9ab086eb0e54ef54c0aaacd3b1f) include it. So, for simplicity I'll decline your pull request (since it is implemented now) but I'm fully appreciate your help!

**Closed** 2024-05-10 14:10 UTC
